Add HTTP2 mode
shadowsocks/v2ray-plugin pull request #134
Opened 2019-09-25 07:11 UTC by cute

2019-12-30 09:54 UTC, madeye commented on main.go
> +	case "http":
Maybe `http2` is better.

2019-12-30 09:55 UTC, madeye requested changes
Use `http2` protocol keyword.

2020-01-18 11:01 UTC, Mygod commented
Why do we need this? Would this work with CDNs that support HTTP/2? (last time I check it is not the case)

2026-07-09 07:03 UTC, madeye commented
Closing as abandoned: opened 2019-09, merge conflicts with current master, no activity toward rebase. Please reopen against current master if still relevant.

2026-07-09 07:03 UTC, closed without merging